# Generated by Django 4.2.7 on 2023-12-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_alter_articles_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='fault',
            field=models.TextField(default='-', max_length=255, verbose_name='Недостатки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(max_length=250, verbose_name='Имя пользователя'),
        ),
    ]
