# Generated by Django 4.2.7 on 2023-12-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articles_fault_alter_articles_anons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='anons',
            new_name='dost',
        ),
    ]
